baseurl = "http://www.ethanmad.com/"
title = "Ethan Madison"
languageCode = "en-us"
MetaDataFormat = "toml"
copyright = "&copy; Ethan Madison 2015"
theme = "vienna"


[params]
  twitter = "_ethanmad"
  github = "ethanmad"
  linkedin = "ethanmadison"
  googleplus = "ethanmad"
  author = "Ethan Madison"
  contact = "mailto:hello@ethanmad.com"
  bio = "I'm a high-school senior and software developer."
  subtitle = "is a high-school senior and software developer."
