baseurl = "https://www.ethanmad.com/"
title = "Ethan Madison's website"
languageCode = "en-us"
MetaDataFormat = "toml"
theme = "hugo-xmin"
footnotereturnlinkcontents = "↩"
PygmentsStyle = "tango"

[[menu.main]]
    name = "Home"
    url = ""
    weight = 1
[[menu.main]]
    name = "About"
    url = "about/"
    weight = 2
[[menu.main]]
    name = "Projects"
    url = "projects/"
    weight = 3
[[menu.main]]
    name = "Tags"
    url = "tags/"
    weight = 4

[params]
    description = "Ethan Madison's website"
    footer = "Content on this site is [CC-BY-SA](https://creativecommons.org/licenses/by-sa/4.0)"
    avatar = "/about/headshot-circle-fs8.png"
