baseurl = "http://www.ethanmad.com/"
title = "Ethan Madison"
languageCode = "en-us"
MetaDataFormat = "toml"
copyright = "&copy; Ethan Madison 2015"
theme = "losangeles"


[params]
  twitter = "_ethanmad"
  github = "ethanmad"
  linkedin = "ethanmadison"
  googleplus = "ethanmad"
  keybase = "ethanmad"
  author = "Ethan Madison"
  contact = "mailto:hello@ethanmad.com"
  avatar = "/images/avatar.png"
  bio = "A freshman at University of Michigan, software developer, entrepreneur, drummer, and fencer from Los Angeles."
  subtitle = "is a freshman at University of Michigan, software developer, entrepreneur, drummer, and fencer from Los Angeles."
  themecolor = "#78839F"
