baseurl = "http://www.ethanmad.com/"
title = "Ethan Madison"
languageCode = "en-us"
MetaDataFormat = "toml"
copyright = "&copy; Ethan Madison 2015"
theme = "losangeles"


[params]
  github = "ethanmad"
  linkedin = "ethanmadison"
  googleplus = "ethanmad"
  author = "Ethan Madison"
  contact = "mailto:hello@ethanmad.com"
  avatar = "static/images/avatar.jpg"
  bio = "I'm a high-school senior, software developer, entrepreneur, drummer, and fencer from Los Angeles."
  subtitle = "is a high-school senior, software developer, drummer, and fencer from Los Angeles."
