baseurl = "https://www.ethanmad.com/"
title = "Ethan Madison's website"
languageCode = "en-us"
MetaDataFormat = "toml"
copyright = "&copy; Ethan Madison 2021"
theme = "hugo-xmin"
footnotereturnlinkcontents = "↩"
PygmentsStyle = "friendly"

[[menu.main]]
    name = "Home"
    url = ""
    weight = 1
[[menu.main]]
    name = "About"
    url = "about/"
    weight = 2
[[menu.main]]
    name = "Projects"
    url = "projects/"
    weight = 3
[[menu.main]]
    name = "Tags"
    url = "tags/"
    weight = 4

[params]
    description = "Ethan Madison's website"
    footer = "&copy; Ethan Madison 2021"
    avatar = "/about/headshot-circle-fs8.png"
