baseurl = "https://www.ethanmad.com/"
title = "Ethan Madison"
languageCode = "en-us"
MetaDataFormat = "toml"
copyright = "&copy; Ethan Madison 2016"
theme = "vienna"


[params]
  github = "ethanmad"
  linkedin = "ethanmadison"
  googleplus = "ethanmad"
  keybase = "ethanmad"
  author = "Ethan Madison"
  contact = "mailto:hello@ethanmad.com"
  avatar = "/images/avatar.png"
  bio = "A computer science and pre-med student at the University of Michigan, software developer, and fencer."
  subtitle = "is a computer science and pre-med student at the University of Michigan, software developer, and fencer."
  themecolor = "#D9B17E"
