baseurl = "http://www.ethanmad.com/"
title = "Ethan Madison"
author = "Ethan Madison"
copyright = "Copyright (c) 2015, Ethan Madison; all rights reserved."
canonifyurls = true
paginate = 3

# Needed by Theme demos in exampleSite.
[params]
  DateForm = "Mon, Jan 2, 2006"

