baseurl = "http://www.ethanmad.com/"
title = "Ethan Madison"
author = "Ethan Madison"
copyright = "Copyright (c) 2015, Ethan Madison; all rights reserved."
canonifyurls = true
paginate = 3

[params]
  twitter = "_ethanmad"
  github = "ethanmad"
  stackoverflow = "ethanmad"
  linkedin = "ethanmadison"
  author = "Ethan Madison"
  contact = "mailto:hello@ethanmad.com"
